import {
  AlignLeft,
  Banknote,
  CircleAlert,
  Clapperboard,
  Code,
  Headset,
  LayoutPanelLeft,
  Library,
  MoveVertical,
  RotateCcw,
  Send,
  SeparatorHorizontal,
  Shapes,
  Award,
  BadgePercent,
  BookOpen,
  Box,
  CircleHelp,
  Clock,
  Columns3,
  FileText,
  Flame,
  GalleryHorizontal,
  Gift,
  Grid3x3,
  Heart,
  Image,
  Images,
  LayoutGrid,
  LayoutPanelTop,
  LayoutTemplate,
  List,
  ListOrdered,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquareQuote,
  Newspaper,
  Package,
  PanelBottom,
  PanelTop,
  Percent,
  Play,
  Presentation,
  Quote,
  Rows3,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tag,
  Tags,
  Text,
  Timer,
  Truck,
  Type,
  User,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";
import type { SectionCategory } from "@pai/theme-sdk";

const ICONS: Record<string, LucideIcon> = {
  banknote: Banknote,
  circlealert: CircleAlert,
  alertcircle: CircleAlert,
  clapperboard: Clapperboard,
  code: Code,
  headset: Headset,
  layoutpanelleft: LayoutPanelLeft,
  library: Library,
  movevertical: MoveVertical,
  rotateccw: RotateCcw,
  history: RotateCcw,
  send: Send,
  separatorhorizontal: SeparatorHorizontal,
  divider: SeparatorHorizontal,
  shapes: Shapes,
  alignleft: AlignLeft,
  award: Award,
  badgepercent: BadgePercent,
  bookopen: BookOpen,
  box: Box,
  circlehelp: CircleHelp,
  helpcircle: CircleHelp,
  faq: CircleHelp,
  clock: Clock,
  columns: Columns3,
  columns3: Columns3,
  filetext: FileText,
  flame: Flame,
  galleryhorizontal: GalleryHorizontal,
  gallery: GalleryHorizontal,
  gift: Gift,
  grid: Grid3x3,
  grid3x3: Grid3x3,
  heart: Heart,
  image: Image,
  images: Images,
  layoutgrid: LayoutGrid,
  layoutpaneltop: LayoutPanelTop,
  layouttemplate: LayoutTemplate,
  list: List,
  listordered: ListOrdered,
  mail: Mail,
  newsletter: Mail,
  mappin: MapPin,
  megaphone: Megaphone,
  announcement: Megaphone,
  menu: Menu,
  messagesquarequote: MessageSquareQuote,
  testimonial: MessageSquareQuote,
  newspaper: Newspaper,
  package: Package,
  panelbottom: PanelBottom,
  paneltop: PanelTop,
  percent: Percent,
  play: Play,
  presentation: Presentation,
  slideshow: Presentation,
  quote: Quote,
  rows: Rows3,
  rows3: Rows3,
  search: Search,
  shieldcheck: ShieldCheck,
  shoppingbag: ShoppingBag,
  shoppingcart: ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  tags: Tags,
  text: Text,
  timer: Timer,
  truck: Truck,
  type: Type,
  user: User,
  users: Users,
  video: Video,
};

const CATEGORY_ICONS: Record<SectionCategory, LucideIcon> = {
  header: PanelTop,
  footer: PanelBottom,
  hero: Image,
  products: ShoppingBag,
  collections: LayoutGrid,
  content: AlignLeft,
  media: Images,
  "social-proof": Star,
  marketing: Megaphone,
  template: LayoutTemplate,
};

/** Resolve a lucide icon name from a section schema ("image", "LayoutGrid", "layout-grid" …). */
export function sectionIcon(name: string | undefined, category?: SectionCategory): LucideIcon {
  if (name) {
    const key = name.toLowerCase().replace(/[^a-z0-9]/g, "");
    const hit = ICONS[key] ?? ICONS[key.replace(/icon$/, "")];
    if (hit) return hit;
  }
  return (category && CATEGORY_ICONS[category]) || LayoutTemplate;
}

export const CATEGORY_LABELS: Record<SectionCategory, string> = {
  hero: "Hero & banners",
  products: "Products",
  collections: "Collections",
  content: "Text & content",
  media: "Images & video",
  "social-proof": "Reviews & trust",
  marketing: "Marketing",
  template: "Page content",
  header: "Header",
  footer: "Footer",
};

export const CATEGORY_ORDER: SectionCategory[] = ["hero", "products", "collections", "content", "media", "social-proof", "marketing", "template", "header", "footer"];
