import {
  BadgePercent,
  Bell,
  ChartColumn,
  Code,
  CreditCard,
  FileText,
  Globe,
  House,
  Image,
  LifeBuoy,
  ListTree,
  Newspaper,
  Package,
  Palette,
  Plug,
  Receipt,
  Settings,
  ShieldAlert,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  Truck,
  TriangleAlert,
  Users,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  home: House,
  orders: ShoppingBag,
  products: Package,
  customers: Users,
  discounts: BadgePercent,
  analytics: ChartColumn,
  themes: Palette,
  pages: FileText,
  blog: Newspaper,
  navigation: ListTree,
  media: Image,
  domains: Globe,
  preferences: SlidersHorizontal,
  settings: Settings,
  support: LifeBuoy,
  store: Store,
  checkout: ShoppingCart,
  delivery: Truck,
  payments: CreditCard,
  apps: Plug,
  bell: Bell,
  billing: Receipt,
  shield: ShieldAlert,
  code: Code,
  danger: TriangleAlert,
};
