import type { Catalog } from "./types";

export const beauty: Catalog = {
  key: "beauty",
  vendor: "Bloom Beauty",
  freeShippingOver: 2500,
  qty: [[1, 70], [2, 25], [3, 5]],
  collections: [
    { slug: "skincare", title: "Skincare", description: "Serums, cleansers and moisturisers for humid-weather skin.", img: "serumDropper" },
    { slug: "makeup", title: "Makeup", description: "Long-wear lips, eyes and glow — shades made for South Asian skin tones.", img: "makeupFlatlay" },
    { slug: "fragrance", title: "Fragrance", description: "Signature scents for day and night.", img: "perfumeRose" },
    { slug: "hair-body", title: "Hair & Body", description: "Nourishing oils, butters and hair care rituals.", img: "coconutOil" },
    { slug: "gift-sets", title: "Gift Sets", description: "Beautifully boxed routines — perfect for Eid and birthdays.", img: "skincareSet" },
  ],
  products: [
    { t: "Vitamin C Brightening Serum (30 ml)", price: 1850, cmp: 2200, img: ["serumDropper", "amberDropper", "dropperHand"], type: "Serum", col: ["skincare"], feat: true, pop: 3,
      d: "15% stabilised vitamin C with ferulic acid to fade dark spots and boost radiance.", h: ["15% ethyl ascorbic acid", "Fragrance free, suits sensitive skin", "Visible glow in 4 weeks"], tags: ["vitamin-c", "brightening", "bestseller"] },
    { t: "Hyaluronic Acid Hydrating Serum (30 ml)", price: 1650, img: ["serumStones", "amberDropper"], type: "Serum", col: ["skincare"], pop: 2,
      d: "Multi-weight hyaluronic acid for plump, bouncy skin — lightweight enough for Dhaka humidity.", h: ["5 types of hyaluronic acid", "Oil free", "Layer under moisturiser"], tags: ["hydration"] },
    { t: "Gentle Foaming Cleanser (150 ml)", price: 1150, img: ["cleanserBottle", "creamTube"], type: "Cleanser", col: ["skincare"], pop: 2.5,
      d: "A pH-balanced gel cleanser that removes sunscreen and grime without stripping.", h: ["pH 5.5", "Sulphate free", "Dermatologist tested"], tags: ["cleanser"] },
    { t: "Daily Moisturiser SPF 30 (50 ml)", price: 1450, img: ["lotionTube", "creamJar"], type: "Moisturiser", col: ["skincare"], feat: true, pop: 2,
      d: "Featherlight moisturiser with broad-spectrum SPF 30 and no white cast.", h: ["SPF 30 PA+++", "No white cast", "Non-comedogenic"], tags: ["spf", "moisturiser"] },
    { t: "Charcoal Detox Clay Mask", price: 1250, img: ["charcoalJars", "facial"], type: "Mask", col: ["skincare"], pop: 1,
      d: "Activated charcoal and kaolin clay to draw out impurities and minimise pores.", h: ["Use 2× a week", "Deep cleans pores", "With soothing aloe"], tags: ["mask"] },
    { t: "Ceramide Barrier Repair Cream (50 g)", price: 1750, img: ["creamJar", "gelJar"], type: "Moisturiser", col: ["skincare"], pop: 1.2,
      d: "Rich ceramide cream that restores a damaged skin barrier overnight.", h: ["3 essential ceramides", "Niacinamide 4%", "Fragrance free"], tags: ["barrier", "night"] },
    { t: "Rose Water Balancing Toner (200 ml)", price: 850, img: ["tonerPink", "whiteBottles"], type: "Toner", col: ["skincare"], pop: 1.5,
      d: "Alcohol-free toner with Damask rose water and glycerin.", h: ["Alcohol free", "Refreshing mist or pad", "Suits all skin types"], tags: ["toner"] },
    { t: "Complete Glow Skincare Set", price: 4950, cmp: 5800, img: ["skincareSet", "skincareBox", "productsLineup"], type: "Gift Set", col: ["gift-sets", "skincare"], feat: true, pop: 1,
      d: "Cleanser, vitamin C serum, moisturiser and toner — a full routine in a gift box.", h: ["4 full-size products", "Save 15% vs buying separately", "Gift-ready box"], tags: ["gift", "routine"] },
    { t: "Matte Velvet Lipstick", price: 950, img: ["lipstick", "makeupFlatlay"], type: "Lipstick", col: ["makeup"], feat: true, pop: 3,
      d: "Weightless, transfer-resistant matte colour that lasts up to 12 hours.", h: ["12-hour wear", "Enriched with vitamin E", "Cruelty free"], opt: [{ name: "Shade", values: ["Ruby Red", "Nude Rose", "Berry Crush", "Coral Pop"] }], tags: ["lipstick", "matte"] },
    { t: "35-Shade Eyeshadow Palette", price: 2450, img: ["palette", "eyeshadow"], type: "Eyeshadow", col: ["makeup"], pop: 1.3,
      d: "Mattes, shimmers and metallics for every look from office to wedding.", h: ["35 blendable shades", "Highly pigmented", "Mirror included"], tags: ["eyes"] },
    { t: "Radiant Glow Blush & Highlighter Duo", price: 1650, img: ["makeupMarble", "makeupFlatlay"], type: "Face", col: ["makeup"], pop: 1,
      d: "A buildable blush and a luminous highlighter in one compact.", h: ["Silky baked formula", "Buildable colour", "Travel friendly"], tags: ["face"] },
    { t: "Pro Makeup Brush Set (12 pcs)", price: 1850, img: ["brushesFlat", "makeupFlatlay"], type: "Tools", col: ["makeup", "gift-sets"], pop: 1,
      d: "Ultra-soft synthetic brushes for face and eyes, with a travel pouch.", h: ["12 essential brushes", "Vegan synthetic bristles", "Includes pouch"], tags: ["tools"] },
    { t: "Long-Wear Nail Lacquer", price: 450, img: ["nailPolish", "nails"], type: "Nails", col: ["makeup"], pop: 1.5,
      d: "Glossy, chip-resistant nail colour in two coats.", opt: [{ name: "Shade", values: ["Sunset Orange", "Lemon Zest", "Cherry", "Midnight"] }], tags: ["nails"] },
    { t: "Nourishing Lip Balm", price: 350, img: ["lipBalm"], type: "Lip Care", col: ["makeup", "hair-body"], pop: 2, d: "Shea and beeswax balm for soft, hydrated lips.", tags: ["lips"] },
    { t: "Peach Blossom Eau de Parfum (50 ml)", price: 3950, img: ["perfumeRose", "perfumePeach"], type: "Perfume", col: ["fragrance"], feat: true, pop: 1,
      d: "A soft floral with notes of peach, rose and white musk.", h: ["Top: peach, bergamot", "Heart: rose, jasmine", "Base: white musk, vanilla"], tags: ["perfume", "floral"] },
    { t: "Midnight Oud Eau de Parfum (50 ml)", price: 5450, img: ["perfumeBlack", "perfumePeach"], type: "Perfume", col: ["fragrance"], pop: 0.7,
      d: "A deep, long-lasting evening scent with oud, amber and saffron.", h: ["8+ hour longevity", "Top: saffron", "Base: oud, amber"], tags: ["perfume", "oud"] },
    { t: "Aqua Homme Eau de Toilette (100 ml)", price: 4250, img: ["perfumeBlue", "perfumeTeal"], type: "Perfume", col: ["fragrance"], pop: 0.8,
      d: "Fresh aquatic fragrance with citrus and cedarwood.", h: ["Fresh & clean", "Daytime signature", "100 ml"], tags: ["perfume", "men"] },
    { t: "Cold-Pressed Coconut Body Oil", price: 750, img: ["coconutOil", "oilHands"], type: "Body Oil", col: ["hair-body"], pop: 1.5, d: "Virgin coconut oil for skin and hair — no additives.", tags: ["natural", "hair"] },
    { t: "Curl & Wave Hair Care Trio", price: 2250, img: ["hairCare", "hairMask"], type: "Hair Care", col: ["hair-body", "gift-sets"], pop: 0.8, d: "Shampoo, conditioner and curl cream for defined, frizz-free waves.", tags: ["hair"] },
    { t: "Whipped Shea Body Butter (250 g)", price: 1150, img: ["bodyCream", "creamJar"], type: "Body Care", col: ["hair-body"], pop: 1.2, d: "Rich shea and cocoa butter for dry winter skin.", tags: ["body"] },
  ],
  blog: [
    { title: "The 4-Step Skincare Routine for Humid Weather", excerpt: "Heavy creams melt off in Dhaka's humidity. Here's a lightweight routine that actually works.", cover: "skincareSet", tags: ["routine", "skincare"],
      points: [["Cleanse", "A gentle gel cleanser morning and night."], ["Treat", "Vitamin C in the morning, hyaluronic acid at night."], ["Protect", "SPF every single day — even when it's cloudy."]] },
    { title: "Vitamin C 101: Everything You Need to Know", excerpt: "How to use vitamin C without irritation, and why it's worth adding to your routine.", cover: "serumDropper", tags: ["ingredients"],
      points: [["Start slow", "Use every other morning for the first two weeks."], ["Store it right", "Keep away from sunlight to prevent oxidation."], ["Pair with SPF", "Vitamin C boosts your sunscreen's protection."]] },
    { title: "Bridal Makeup Checklist for Holud, Wedding & Reception", excerpt: "Three looks, one kit — what to pack for a Bangladeshi wedding week.", cover: "makeupFlatlay", tags: ["bridal", "makeup"],
      points: [["Holud glow", "Dewy skin, coral lips and a golden highlighter."], ["Wedding day", "Long-wear foundation and a classic red lip."], ["Reception", "Smoky eyes and nude lips for the evening lights."]] },
  ],
  about: [
    "{store} was founded by two sisters who struggled to find authentic skincare in Bangladesh. We import directly from brands and authorised distributors — no grey market, ever.",
    "Our formulas are chosen for South Asian skin and our hot, humid climate, and every product is stored in temperature-controlled rooms.",
    "Need help with a routine? Message our skincare advisors on WhatsApp for a free consultation.",
  ],
  perks: ["100% authentic, batch-coded", "Free skincare consultation"],
  reviews: [
    "My skin feels so much better after two weeks.", "Authentic product, checked the batch code.", "Lovely texture, absorbs quickly.", "The shade is perfect for my skin tone.",
    "Smells amazing and lasts all day.", "Beautiful packaging, great for gifting.", "No breakouts, suits my sensitive skin.",
  ],
};
