import type { Catalog } from "./types";

export const electronics: Catalog = {
  key: "electronics",
  vendor: "Volt",
  freeShippingOver: 10000,
  qty: [[1, 92], [2, 8]],
  collections: [
    { slug: "smartphones", title: "Smartphones", description: "Official and verified-import flagships and mid-rangers with warranty.", img: "iphonePro" },
    { slug: "laptops-tablets", title: "Laptops & Tablets", description: "Ultrabooks, creator laptops and tablets for work and study.", img: "laptopWood" },
    { slug: "audio", title: "Audio", description: "Headphones, earbuds and speakers tuned for every budget.", img: "headphonesYellow" },
    { slug: "wearables", title: "Smartwatches", description: "Track your health, notifications and workouts.", img: "smartwatchBlack" },
    { slug: "gaming", title: "Gaming", description: "Controllers, keyboards and gear for serious play.", img: "gamingSetup" },
    { slug: "cameras-drones", title: "Cameras & Drones", description: "Capture everything — from instant prints to 4K aerials.", img: "mirrorlessKit" },
  ],
  products: [
    { t: "Apple iPhone 15 Pro", price: 154999, img: ["iphonePro", "phoneFloat", "iphoneX"], vendor: "Apple", type: "Smartphone", col: ["smartphones"], feat: true, pop: 1.5,
      d: "Titanium design, A17 Pro chip and a pro camera system with 5× telephoto on the Max-class sensor.", specs: [["Display", "6.1\" Super Retina XDR, 120Hz"], ["Chip", "A17 Pro"], ["Camera", "48MP main + 12MP ultra-wide + 12MP 3× tele"], ["Battery", "Up to 23 hrs video"], ["Warranty", "1 year official"]],
      opt: [{ name: "Storage", values: ["128GB", "256GB", "512GB"] }, { name: "Color", values: ["Natural Titanium", "Black Titanium"] }], delta: { "256GB": 18000, "512GB": 42000 }, stock: [2, 9], tags: ["apple", "iphone", "5g"] },
    { t: "Samsung Galaxy S24 Ultra", price: 149999, cmp: 159999, img: ["galaxyUltra", "android", "phoneDark"], vendor: "Samsung", type: "Smartphone", col: ["smartphones"], feat: true, pop: 1.3,
      d: "Galaxy AI, a built-in S Pen and a 200MP camera in a titanium frame.", specs: [["Display", "6.8\" QHD+ Dynamic AMOLED 2X"], ["Processor", "Snapdragon 8 Gen 3 for Galaxy"], ["Camera", "200MP + 50MP + 12MP + 10MP"], ["Battery", "5000 mAh, 45W"], ["Warranty", "1 year official"]],
      opt: [{ name: "Storage", values: ["256GB", "512GB"] }, { name: "Color", values: ["Titanium Black", "Titanium Gray"] }], delta: { "512GB": 16000 }, stock: [2, 8], tags: ["samsung", "android", "5g"] },
    { t: "Xiaomi Redmi Note 13 Pro", price: 32999, img: ["android", "phoneHand"], vendor: "Xiaomi", type: "Smartphone", col: ["smartphones"], pop: 3,
      d: "200MP camera, 120Hz AMOLED and 67W turbo charging — the mid-range champion.", specs: [["Display", "6.67\" 1.5K AMOLED, 120Hz"], ["Processor", "Snapdragon 7s Gen 2"], ["Battery", "5100 mAh, 67W"], ["Warranty", "1 year official"]],
      opt: [{ name: "Variant", values: ["8GB/128GB", "8GB/256GB", "12GB/512GB"] }], delta: { "8GB/256GB": 3000, "12GB/512GB": 8000 }, stock: [8, 25], tags: ["xiaomi", "android", "budget"] },
    { t: "Apple MacBook Air 13\" M3", price: 139999, img: ["laptopWood", "laptopSilver", "laptopPurple"], vendor: "Apple", type: "Laptop", col: ["laptops-tablets"], feat: true, pop: 1,
      d: "Strikingly thin, fanless and fast — with up to 18 hours of battery life.", specs: [["Chip", "Apple M3, 8-core CPU"], ["Display", "13.6\" Liquid Retina"], ["Weight", "1.24 kg"], ["Battery", "Up to 18 hours"]],
      opt: [{ name: "Configuration", values: ["8GB / 256GB", "16GB / 512GB"] }], delta: { "16GB / 512GB": 30000 }, stock: [2, 6], tags: ["apple", "macbook"] },
    { t: "ASUS Zenbook 14 OLED", price: 104999, img: ["laptopRainbow", "laptopGlow"], vendor: "ASUS", type: "Laptop", col: ["laptops-tablets"], pop: 0.8,
      d: "Intel Core Ultra 7 with a gorgeous 3K OLED display in a 1.2 kg chassis.", specs: [["Processor", "Intel Core Ultra 7 155H"], ["Memory", "16GB LPDDR5X"], ["Storage", "1TB PCIe 4.0 SSD"], ["Display", "14\" 3K OLED 120Hz"]], stock: [2, 6], tags: ["asus", "windows", "oled"] },
    { t: "Dell Inspiron 15 3530", price: 72999, cmp: 78999, img: ["laptopWin", "laptopDesk"], vendor: "Dell", type: "Laptop", col: ["laptops-tablets"], pop: 1,
      d: "A dependable everyday laptop for students and small offices.", specs: [["Processor", "Intel Core i5-1335U"], ["Memory", "8GB DDR4"], ["Storage", "512GB SSD"], ["Display", "15.6\" FHD 120Hz"]], stock: [3, 10], tags: ["dell", "windows", "student"] },
    { t: "Apple iPad Air 11\" (M2)", price: 84999, img: ["ipad", "tablet"], vendor: "Apple", type: "Tablet", col: ["laptops-tablets"], pop: 0.8,
      d: "Serious performance in a thin and light design — works with Apple Pencil Pro.", specs: [["Chip", "Apple M2"], ["Display", "11\" Liquid Retina"], ["Camera", "12MP landscape front camera"]],
      opt: [{ name: "Storage", values: ["128GB", "256GB"] }], delta: { "256GB": 12000 }, stock: [2, 7], tags: ["apple", "ipad"] },
    { t: "Sony WH-1000XM5 Noise Cancelling Headphones", price: 42999, cmp: 46999, img: ["headphonesAnc", "headphonesGrey", "headphonesDark"], vendor: "Sony", type: "Headphones", col: ["audio"], feat: true, pop: 1.3,
      d: "Industry-leading noise cancellation with 30 hours of battery life.", specs: [["Battery", "30 hours (ANC on)"], ["Charging", "3 min = 3 hours playback"], ["Codec", "LDAC, AAC, SBC"]],
      opt: [{ name: "Color", values: ["Black", "Silver"] }], stock: [3, 10], tags: ["sony", "anc", "wireless"] },
    { t: "Apple AirPods Pro (2nd generation)", price: 29999, img: ["airpodsPro", "earbudsWhite"], vendor: "Apple", type: "Earbuds", col: ["audio"], pop: 1.5,
      d: "Up to 2× more active noise cancellation, Adaptive Audio and USB-C MagSafe case.", specs: [["Chip", "H2"], ["Battery", "Up to 6 hrs (30 hrs with case)"], ["Rating", "IP54"]], stock: [4, 14], tags: ["apple", "anc"] },
    { t: "QCY T13 ANC Wireless Earbuds", price: 2490, cmp: 2990, img: ["earbudsRed", "earbudsCases"], vendor: "QCY", type: "Earbuds", col: ["audio"], pop: 4,
      d: "Budget-friendly ANC earbuds with a 4-mic ENC setup for clear calls.", specs: [["ANC", "Up to 28 dB"], ["Battery", "30 hrs total"], ["Bluetooth", "5.3"]], stock: [20, 60], tags: ["budget", "earbuds"] },
    { t: "JBL Flip 6 Portable Speaker", price: 13999, img: ["speakerFlip", "speakerRgb"], vendor: "JBL", type: "Speaker", col: ["audio"], pop: 1.4,
      d: "Bold JBL Pro Sound in a rugged IP67 waterproof body.", specs: [["Output", "20W woofer + 10W tweeter"], ["Battery", "12 hours"], ["Rating", "IP67"]],
      opt: [{ name: "Color", values: ["Black", "Blue", "Red"] }], stock: [4, 12], tags: ["jbl", "bluetooth", "speaker"] },
    { t: "Apple Watch Series 9 GPS 45mm", price: 52999, img: ["smartwatchBlack", "smartwatchApps", "smartwatchWrist"], vendor: "Apple", type: "Smartwatch", col: ["wearables"], feat: true, pop: 0.9,
      d: "A brighter display, double-tap gesture and advanced health sensors.", specs: [["Chip", "S9 SiP"], ["Display", "Always-On Retina, 2000 nits"], ["Health", "ECG, blood oxygen, temperature"]],
      opt: [{ name: "Color", values: ["Midnight", "Starlight"] }], stock: [2, 8], tags: ["apple", "watch"] },
    { t: "Minimal AMOLED Smartwatch", price: 5990, cmp: 6990, img: ["smartwatchWhite", "smartwatchWrist"], vendor: "Volt Select", type: "Smartwatch", col: ["wearables"], pop: 2,
      d: "1.43\" AMOLED, Bluetooth calling and 14-day battery at a price that makes sense.", specs: [["Display", "1.43\" AMOLED"], ["Battery", "Up to 14 days"], ["Water resistance", "5 ATM"]], stock: [10, 30], tags: ["budget", "watch"] },
    { t: "PlayStation 5 DualSense Controller", price: 8499, img: ["ps5Controller", "gamingSetup"], vendor: "Sony", type: "Controller", col: ["gaming"], pop: 1.2,
      d: "Haptic feedback and adaptive triggers for next-gen immersion.", specs: [["Connectivity", "Bluetooth, USB-C"], ["Battery", "Built-in rechargeable"]], stock: [5, 15], tags: ["playstation", "gaming"] },
    { t: "DualShock 4 Wireless Controller", price: 5299, cmp: 5999, img: ["ps4Controller"], vendor: "Sony", type: "Controller", col: ["gaming"], pop: 0.9,
      d: "The classic PS4 controller with touch pad and light bar.", specs: [["Connectivity", "Bluetooth, Micro-USB"], ["Compatibility", "PS4, PC"]], stock: [5, 15], tags: ["playstation", "gaming"] },
    { t: "Keychron K2 Wireless Mechanical Keyboard", price: 9999, img: ["mechKeyboard", "keyboardSlim"], vendor: "Keychron", type: "Keyboard", col: ["gaming"], pop: 1,
      d: "Compact 75% layout with hot-swappable switches and Mac/Windows keycaps.", specs: [["Layout", "75%, 84 keys"], ["Connectivity", "Bluetooth 5.1 / USB-C"], ["Battery", "4000 mAh"]],
      opt: [{ name: "Switch", values: ["Red", "Brown", "Blue"] }], stock: [3, 10], tags: ["keyboard", "mechanical"] },
    { t: "NVIDIA GeForce RTX 4070 Graphics Card", price: 78999, img: ["gpu", "gamingPc"], vendor: "NVIDIA", type: "Graphics Card", col: ["gaming"], pop: 0.4,
      d: "DLSS 3 and ray tracing for smooth 1440p gaming.", specs: [["Memory", "12GB GDDR6X"], ["Boost clock", "2.48 GHz"], ["Power", "200W"]], stock: [1, 4], tags: ["pc", "gpu"] },
    { t: "Xiaomi 20000mAh Power Bank 3", price: 2450, img: ["powerbank", "techFlatlay"], vendor: "Xiaomi", type: "Power Bank", col: ["cameras-drones", "smartphones"], pop: 3,
      d: "Charge your phone up to 4 times with 22.5W fast charging.", specs: [["Capacity", "20000 mAh"], ["Output", "22.5W max"], ["Ports", "2× USB-A, 1× USB-C"]], stock: [15, 50], tags: ["accessory", "charging"] },
    { t: "DJI Mini 4 Pro Drone", price: 114999, img: ["droneFold", "droneWhite"], vendor: "DJI", type: "Drone", col: ["cameras-drones"], feat: true, pop: 0.3,
      d: "Under 249 g with omnidirectional obstacle sensing and 4K/60fps HDR video.", specs: [["Weight", "< 249 g"], ["Video", "4K/60fps HDR"], ["Flight time", "34 minutes"]], stock: [1, 4], tags: ["dji", "drone"] },
    { t: "Canon EOS R50 Mirrorless Kit (18-45mm)", price: 94999, img: ["mirrorlessKit", "dslr"], vendor: "Canon", type: "Camera", col: ["cameras-drones"], pop: 0.5,
      d: "A compact creator camera with 4K video and fast Dual Pixel autofocus.", specs: [["Sensor", "24.2MP APS-C"], ["Video", "4K 30p uncropped"], ["Lens", "RF-S 18-45mm"]], stock: [1, 5], tags: ["canon", "camera"] },
    { t: "Polaroid Now Instant Camera", price: 16999, img: ["polaroid"], vendor: "Polaroid", type: "Camera", col: ["cameras-drones"], ext: true, pop: 0.5,
      d: "Point, shoot and print — autofocus analog instant camera.", specs: [["Film", "i-Type & 600"], ["Battery", "Rechargeable, USB"]], stock: [2, 6], tags: ["camera", "gift"] },
  ],
  blog: [
    { title: "iPhone 15 Pro vs Galaxy S24 Ultra: Which Flagship Should You Buy?", excerpt: "We used both phones for two weeks in Dhaka traffic, rain and low light — here's our verdict.", cover: "galaxyUltra", tags: ["comparison", "smartphones"],
      points: [["Camera", "The S24 Ultra's zoom is unmatched; the iPhone wins on video and skin tones."], ["Battery", "Both last a full day; Samsung charges faster with 45W."], ["Value", "Official warranty matters — always check the IMEI before buying."]] },
    { title: "How to Spot a Fake Charger (and Why It Matters)", excerpt: "Cheap chargers can damage your phone's battery. Five quick checks before you buy.", cover: "powerbank", tags: ["guide", "safety"],
      points: [["Check the weight", "Genuine chargers feel dense; fakes are noticeably light."], ["Look at the print", "Blurry logos and spelling mistakes are red flags."], ["Buy from verified sellers", "Every Volt product ships with a warranty card and invoice."]] },
    { title: "Best Budget Earbuds Under ৳3,000 in 2026", excerpt: "You don't need to spend a fortune for good sound and ANC. Our top picks tested.", cover: "earbudsRed", tags: ["audio", "budget"],
      points: [["QCY T13 ANC", "Best overall — punchy bass and genuinely useful noise cancelling."], ["Battery life matters", "Look for at least 6 hours per charge."], ["Call quality", "Multi-mic ENC makes a real difference in noisy streets."]] },
  ],
  about: [
    "{store} is Bangladesh's go-to destination for authentic gadgets. We started as a two-person shop in Multiplan Center and now serve thousands of tech lovers every month.",
    "Every product we sell is 100% authentic — official distributor stock or verified imports — and comes with a clear warranty policy.",
    "Our tech team tests every device before dispatch, and our support team is available on WhatsApp 10am–10pm, seven days a week.",
  ],
  perks: ["100% authentic with warranty", "Easy EMI on 20+ bank cards"],
  reviews: [
    "Original product, verified the IMEI myself.", "Packaging was sealed and delivery was super fast.", "Battery backup is great so far.", "Sound quality is amazing for the price.",
    "Best price in Dhaka, compared with 3 shops.", "Warranty card and invoice were included.", "Works perfectly, will buy again.",
  ],
};
