import type { Catalog } from "./types";

const TOP = { name: "Size", values: ["S", "M", "L", "XL"] };
const TOP_XXL = { name: "Size", values: ["M", "L", "XL", "XXL"] };
const WOMEN = { name: "Size", values: ["S", "M", "L", "XL"] };
const WAIST = { name: "Waist", values: ["30", "32", "34", "36"] };
const SHOE_W = { name: "Size", values: ["36", "37", "38", "39", "40"] };
const SHOE_M = { name: "Size", values: ["40", "41", "42", "43", "44"] };

export const fashion: Catalog = {
  key: "fashion",
  vendor: "Aurora Studio",
  freeShippingOver: 3000,
  collections: [
    { slug: "new-arrivals", title: "New Arrivals", description: "Fresh drops for the season — just landed in our Dhaka studio.", img: "shopping", sortOrder: "newest" },
    { slug: "women", title: "Women", description: "Dresses, tops and everyday essentials designed for the modern Bangladeshi woman.", img: "floralWrapDress" },
    { slug: "men", title: "Men", description: "Sharp shirts, denim and outerwear with a tailored fit.", img: "blueShirtMan" },
    { slug: "ethnic-wear", title: "Ethnic Wear", description: "Jamdani, silk and embroidered pieces for Eid, weddings and every festive occasion.", img: "saree" },
    { slug: "accessories", title: "Bags, Shoes & Accessories", description: "Finish the look — handbags, footwear, sunglasses and more.", img: "redHandbag" },
    { slug: "sale", title: "Sale", description: "Limited-time markdowns on customer favourites.", img: "rack", sortOrder: "price-asc" },
  ],
  products: [
    { t: "Classic Crew Neck Cotton Tee", price: 690, cmp: 850, img: ["whiteTee", "whiteTeeMan", "blackTee"], type: "T-Shirt", col: ["men", "new-arrivals"], feat: true, pop: 3,
      d: "Our best-selling everyday tee, cut from 180 GSM combed cotton that stays soft wash after wash.", h: ["100% combed cotton, 180 GSM", "Pre-shrunk, regular fit", "Reinforced shoulder seams"], opt: [TOP, { name: "Color", values: ["White", "Black"] }], tags: ["cotton", "basics", "bestseller"] },
    { t: "Oversized Graphic Tee — Original", price: 890, img: ["graphicTee", "teeShorts"], type: "T-Shirt", col: ["men", "new-arrivals"], pop: 2,
      d: "Relaxed drop-shoulder fit with a bold screen-printed front graphic.", h: ["Heavyweight 220 GSM jersey", "Crack-resistant plastisol print", "Unisex oversized fit"], opt: [TOP], tags: ["streetwear", "graphic"] },
    { t: "Chambray Print Casual Shirt", price: 1650, img: ["printShirt", "denimShirt"], type: "Shirt", col: ["men"], pop: 1.5,
      d: "Lightweight chambray with a subtle all-over print — made for Dhaka summers.", h: ["Breathable cotton chambray", "Button-down collar", "Curved hem, wear tucked or untucked"], opt: [TOP_XXL], tags: ["casual", "summer"] },
    { t: "Premium Formal Shirt — Sky Blue", price: 1850, cmp: 2200, img: ["blueShirtMan", "shirtsFlat"], type: "Shirt", col: ["men", "sale"], feat: true, pop: 2,
      d: "An office staple in wrinkle-resistant twill with a crisp spread collar.", h: ["Easy-iron cotton twill", "Slim fit through chest and waist", "Mother-of-pearl effect buttons"], opt: [TOP_XXL], tags: ["formal", "office"] },
    { t: "Slim-Fit White Dress Shirt", price: 1750, img: ["whiteShirtTie", "shirtsFlat"], type: "Shirt", col: ["men"], pop: 1.2,
      d: "Sharp, bright white poplin shirt that pairs with every suit you own.", h: ["Fine 100s two-ply poplin", "Double-button cuffs", "Slim tailored fit"], opt: [TOP_XXL], tags: ["formal", "wedding"] },
    { t: "Stretch Denim Jeans — Indigo", price: 2450, img: ["jeansStack", "denimStack"], type: "Jeans", col: ["men", "new-arrivals"], feat: true, pop: 2.5,
      d: "Mid-rise slim jeans with 2% stretch for all-day comfort.", h: ["12 oz stretch denim", "Classic five-pocket styling", "Mid-rise, slim-straight leg"], opt: [WAIST], tags: ["denim", "bestseller"] },
    { t: "Distressed Skinny Jeans", price: 2250, cmp: 2790, img: ["jeansRipped", "jeansStack"], type: "Jeans", col: ["women", "sale"], pop: 1.3,
      d: "High-rise skinny jeans with hand-finished rips and a vintage wash.", h: ["Hand-distressed details", "High rise, ankle length", "Super-stretch denim"], opt: [{ name: "Waist", values: ["26", "28", "30", "32"] }], tags: ["denim"] },
    { t: "Slim Chino Pants — Khaki", price: 1950, img: ["chinos", "outfitFlat"], type: "Pants", col: ["men"], pop: 1.4,
      d: "Versatile cotton-stretch chinos that go from office to weekend.", h: ["Cotton with 2% elastane", "Slim tapered leg", "Slant pockets, back welt pockets"], opt: [WAIST], tags: ["chinos", "smart-casual"] },
    { t: "Tailored Trousers — Black", price: 2150, img: ["blackPants", "outfitFlat"], type: "Pants", col: ["men"], pop: 0.8,
      d: "Clean-lined formal trousers in a fluid poly-viscose blend.", h: ["Flat front, pressed crease", "Half-lined for structure", "Extended waistband closure"], opt: [WAIST], tags: ["formal"] },
    { t: "Suede Bomber Jacket — Rust", price: 4950, cmp: 5950, img: ["bomberJacket", "quiltedJacket"], type: "Jacket", col: ["men", "new-arrivals", "sale"], feat: true, pop: 1.2,
      d: "A winter essential in soft faux suede with ribbed trims.", h: ["Premium faux suede shell", "Quilted satin lining", "Two-way zip, inner pocket"], opt: [TOP], tags: ["winter", "outerwear"] },
    { t: "Biker Leather Jacket", price: 8950, img: ["leatherJacket"], type: "Jacket", col: ["men"], pop: 0.6,
      d: "Classic asymmetric biker jacket in genuine lambskin leather.", h: ["Genuine lambskin", "Heavy-duty YKK zips", "Notched lapels with snap studs"], opt: [{ name: "Size", values: ["M", "L", "XL"] }], tags: ["leather", "winter"] },
    { t: "Quilted Puffer Jacket", price: 3950, cmp: 4800, img: ["quiltedJacket", "bomberJacket"], type: "Jacket", col: ["men", "sale"], pop: 0.9,
      d: "Lightweight warmth for chilly December evenings.", h: ["Water-repellent shell", "Recycled poly fill", "Packs into its own pocket"], opt: [TOP], tags: ["winter"] },
    { t: "Two-Piece Navy Suit", price: 14500, img: ["navySuit", "darkSuit", "outfitFlat"], type: "Suit", col: ["men"], feat: true, pop: 0.5,
      d: "Our signature slim suit in Italian-milled wool blend — wedding season ready.", h: ["Wool-blend suiting", "Half-canvas construction", "Free alteration at our Dhanmondi studio"], opt: [{ name: "Size", values: ["38", "40", "42", "44"] }], tags: ["wedding", "formal", "suit"] },
    { t: "Everyday Crewneck Sweatshirt", price: 1890, img: ["whiteSweatshirt", "knitFlatlay"], type: "Sweatshirt", col: ["women", "men"], pop: 1,
      d: "Cloud-soft brushed fleece in a clean, relaxed silhouette.", h: ["Brushed-back cotton fleece", "Ribbed cuffs and hem", "Unisex relaxed fit"], opt: [TOP], tags: ["winter", "basics"] },
    { t: "Off-Shoulder Summer Dress", price: 2650, img: ["whiteDress", "whiteAnarkali"], type: "Dress", col: ["women", "new-arrivals"], feat: true, pop: 1.6,
      d: "Breezy tiered cotton dress with a smocked off-shoulder neckline.", h: ["Lightweight cotton voile", "Fully lined skirt", "Elasticated smocked bodice"], opt: [{ name: "Size", values: ["S", "M", "L"] }], tags: ["summer", "dress"] },
    { t: "Floor-Length Georgette Gown — Red", price: 5450, cmp: 6500, img: ["redGown", "redFloralDress"], type: "Gown", col: ["women", "sale"], feat: true, pop: 1,
      d: "A show-stopping flared georgette gown for holud, receptions and Eid parties.", h: ["Flowing double georgette", "Hidden side zip", "Full circle flare"], opt: [{ name: "Size", values: ["S", "M", "L"] }], tags: ["party", "eid"] },
    { t: "Floral Midi Wrap Dress", price: 2950, img: ["floralWrapDress", "redFloralDress"], type: "Dress", col: ["women", "new-arrivals"], pop: 1.3,
      d: "Printed crepe wrap dress that flatters every body type.", h: ["Soft crepe with floral print", "Adjustable wrap tie", "Midi length"], opt: [WOMEN], tags: ["dress", "floral"] },
    { t: "Corduroy Button Dress — Maroon", price: 2750, img: ["maroonDress"], type: "Dress", col: ["women"], pop: 0.9,
      d: "Fine-wale corduroy shirt dress with a gathered waist.", h: ["Fine-wale cotton corduroy", "Full button placket", "Side seam pockets"], opt: [WOMEN], tags: ["dress", "winter"] },
    { t: "Handloom Dhakai Jamdani Saree", price: 12500, cmp: 14500, img: ["saree", "silkSaree"], type: "Saree", col: ["ethnic-wear", "women", "sale"], feat: true, pop: 1,
      d: "Woven by master weavers in Rupganj — a timeless Dhakai jamdani with zari motifs.", h: ["Handwoven in Narayanganj", "Soft cotton-silk blend, 6 yards", "Comes with unstitched blouse piece"], tags: ["jamdani", "handloom", "eid"] },
    { t: "Katan Silk Bridal Saree", price: 18500, img: ["silkSaree", "saree"], type: "Saree", col: ["ethnic-wear", "women"], pop: 0.6,
      d: "Rich Benarasi-style katan silk with a heavy zari pallu for the big day.", h: ["Pure katan silk", "Heavy zari border and pallu", "Gift-boxed"], tags: ["bridal", "silk", "wedding"] },
    // Extended catalogue (merchant demo)
    { t: "Embroidered Georgette Anarkali — White", price: 4650, img: ["whiteAnarkali", "whiteDress"], type: "Anarkali", col: ["ethnic-wear", "women", "new-arrivals"], ext: true, pop: 1.2,
      d: "Flowing floor-length anarkali with delicate thread embroidery.", h: ["Georgette with inner lining", "Thread and sequin embroidery", "Includes matching dupatta"], opt: [WOMEN], tags: ["eid", "ethnic"] },
    { t: "Three-Piece Salwar Kameez — Green", price: 3450, cmp: 3950, img: ["greenKameez"], type: "Three-Piece", col: ["ethnic-wear", "women", "sale"], ext: true, feat: true, pop: 2,
      d: "Printed lawn three-piece with a chiffon dupatta — our Eid best-seller.", h: ["Premium lawn cotton", "Chiffon dupatta", "Ready-to-wear stitched"], opt: [WOMEN], tags: ["eid", "three-piece", "bestseller"] },
    { t: "Tiered Chiffon Maxi — Teal", price: 3150, img: ["tealMaxi"], type: "Dress", col: ["women"], ext: true, pop: 1,
      d: "Floaty tiered maxi with balloon sleeves and a V neckline.", h: ["Chiffon with satin lining", "Balloon sleeves", "Tie waist"], opt: [WOMEN], tags: ["dress"] },
    { t: "Denim Shirt Dress", price: 2450, img: ["denimDress"], type: "Dress", col: ["women"], ext: true, pop: 0.9,
      d: "Lightweight denim shirt dress — throw on and go.", h: ["Soft washed denim", "Button-through front", "Knee length"], opt: [WOMEN], tags: ["denim", "dress"] },
    { t: "Utility Romper — Olive", price: 1950, cmp: 2400, img: ["romper"], type: "Romper", col: ["women", "sale"], ext: true, pop: 0.8,
      d: "Belted utility romper for weekend brunches.", h: ["Cotton twill", "Self-tie belt", "Adjustable straps"], opt: [WOMEN], tags: ["summer"] },
    { t: "Ruffle Blouse — Blush Pink", price: 1650, img: ["pinkBlouse"], type: "Top", col: ["women", "new-arrivals"], ext: true, pop: 1,
      d: "Romantic off-shoulder ruffle blouse in printed georgette.", h: ["Lightweight georgette", "Elasticated neckline", "Relaxed fit"], opt: [WOMEN], tags: ["top"] },
    { t: "Everyday Jogger Pants — Dusty Pink", price: 1450, img: ["pinkJoggers"], type: "Pants", col: ["women"], ext: true, pop: 1.1,
      d: "Tapered joggers in soft French terry.", h: ["Cotton French terry", "Elastic waist with drawcord", "Cuffed ankles"], opt: [WOMEN], tags: ["loungewear"] },
    { t: "Wool-Blend Long Coat", price: 6950, img: ["coatWoman"], type: "Coat", col: ["women"], ext: true, pop: 0.5,
      d: "A timeless longline coat in a warm wool blend.", h: ["60% wool blend", "Notched lapel", "Fully lined"], opt: [WOMEN], tags: ["winter", "outerwear"] },
    { t: "Tartan Oversized Blazer", price: 5250, img: ["checkBlazer"], type: "Blazer", col: ["women"], ext: true, pop: 0.6,
      d: "Oversized check blazer with padded shoulders.", h: ["Brushed tartan weave", "Single-button front", "Flap pockets"], opt: [WOMEN], tags: ["winter"] },
    { t: "Structured Top-Handle Bag — Red", price: 4450, img: ["redHandbag"], type: "Handbag", col: ["accessories", "new-arrivals"], ext: true, feat: true, pop: 1,
      d: "Glossy structured handbag with a signature turn-lock.", h: ["Vegan patent leather", "Detachable shoulder strap", "Suede-feel lining"], tags: ["bag"] },
    { t: "Quilted Chain Crossbody Bag", price: 3850, img: ["quiltedBag"], type: "Handbag", col: ["accessories"], ext: true, pop: 1,
      d: "Chevron-quilted crossbody with a gold chain strap.", h: ["Quilted faux leather", "Chain and leather strap", "Two inner compartments"], tags: ["bag"] },
    { t: "Rattan & Leather Handbag", price: 3250, img: ["wickerBag"], type: "Handbag", col: ["accessories"], ext: true, pop: 0.7,
      d: "Hand-woven rattan body with tan leather trims.", h: ["Handwoven rattan", "Leather top handle", "Magnetic clasp"], tags: ["bag", "summer"] },
    { t: "Mini Chain Clutch — Blush", price: 1950, img: ["pinkClutch"], type: "Clutch", col: ["accessories", "sale"], cmp: 2450, ext: true, pop: 0.8,
      d: "Colour-block envelope clutch for evenings out.", h: ["Structured faux leather", "Detachable chain", "Fits a phone and cards"], tags: ["bag", "party"] },
    { t: "Leather Crossbody Satchel — Tan", price: 2850, img: ["brownCrossbody"], type: "Handbag", col: ["accessories"], ext: true, pop: 1,
      d: "Minimal everyday satchel in pebbled leather.", h: ["Genuine cowhide", "Adjustable strap", "Flap with magnetic closure"], tags: ["bag", "leather"] },
    { t: "Genuine Leather Bifold Wallet", price: 1250, img: ["wallet"], type: "Wallet", col: ["accessories", "men"], ext: true, pop: 1.5,
      d: "Slim bifold wallet with RFID-blocking lining.", h: ["Full-grain leather", "6 card slots, 2 note compartments", "RFID blocking"], tags: ["leather", "gift"] },
    { t: "Everyday Canvas Sneakers", price: 2450, img: ["sneakerCanvas", "sneakerWhite"], type: "Sneakers", col: ["accessories", "new-arrivals"], ext: true, pop: 1.5,
      d: "Clean low-top sneakers with a cushioned insole.", h: ["Canvas upper", "Vulcanised rubber sole", "Memory foam insole"], opt: [SHOE_M], tags: ["footwear"] },
    { t: "Leather Chelsea Ankle Boots", price: 4850, img: ["ankleBoots"], type: "Boots", col: ["accessories", "women"], ext: true, pop: 0.6,
      d: "Block-heel Chelsea boots in burnished tan leather.", h: ["Genuine leather upper", "Elastic side gussets", "5 cm block heel"], opt: [SHOE_W], tags: ["footwear", "winter"] },
    { t: "Platform Strap Sandals", price: 2150, cmp: 2650, img: ["platformSandals"], type: "Sandals", col: ["accessories", "women", "sale"], ext: true, pop: 1,
      d: "Cross-strap platform sandals with a cork-look sole.", h: ["Padded footbed", "Lightweight EVA platform", "Buckle ankle strap"], opt: [SHOE_W], tags: ["footwear", "summer"] },
    { t: "Printed Stiletto Heels", price: 2950, img: ["heels"], type: "Heels", col: ["accessories", "women"], ext: true, pop: 0.7,
      d: "Pointed-toe stilettos in a vibrant floral print.", h: ["10 cm stiletto heel", "Cushioned insole", "Non-slip sole"], opt: [SHOE_W], tags: ["footwear", "party"] },
    { t: "Classic Leather Oxford — Brown", price: 3950, img: ["brownShoes"], type: "Formal Shoes", col: ["accessories", "men"], ext: true, pop: 0.9,
      d: "Hand-finished cap-toe oxfords for weddings and the office.", h: ["Full-grain leather", "Leather lining", "Resoleable construction"], opt: [SHOE_M], tags: ["footwear", "formal"] },
    { t: "Polarized Round Sunglasses", price: 1450, img: ["roundSunglasses"], type: "Sunglasses", col: ["accessories"], ext: true, pop: 1,
      d: "Retro metal frames with UV400 polarized lenses.", h: ["UV400 protection", "Polarized lenses", "Includes hard case"], tags: ["eyewear", "summer"] },
    { t: "Classic Wayfarer Sunglasses", price: 1350, img: ["wayfarer"], type: "Sunglasses", col: ["accessories", "men"], ext: true, pop: 1,
      d: "The icon — acetate wayfarer frames with dark lenses.", h: ["Acetate frame", "UV400 lenses", "Spring hinges"], tags: ["eyewear"] },
    { t: "Washed Cotton Baseball Cap", price: 650, img: ["cap"], type: "Cap", col: ["accessories", "men"], ext: true, pop: 1.2,
      d: "Vintage-washed six-panel cap with an adjustable strap.", h: ["100% cotton twill", "Adjustable back strap", "One size fits most"], tags: ["cap"] },
  ],
  blog: [
    { title: "Eid Lookbook 2026: Five Outfits for Every Celebration", excerpt: "From jamdani to modern three-pieces — how to dress for Eid morning, family visits and the evening dawat.", cover: "saree", tags: ["eid", "lookbook"],
      points: [["Eid morning", "Keep it light — a pastel lawn three-piece or a crisp cotton panjabi works beautifully in the heat."], ["Family visits", "Layer a printed dupatta over a solid kameez; comfortable, photogenic and easy to move in."], ["The evening dawat", "Bring out the georgette gown or your favourite jamdani with statement jewellery."]] },
    { title: "How to Find Your Perfect Jeans Fit", excerpt: "Slim, straight or skinny? A quick guide to measuring yourself and choosing the right cut.", cover: "jeansStack", tags: ["guide", "denim"],
      points: [["Measure your waist", "Measure around your natural waist and round up — our size chart lists every style in inches."], ["Pick the rise", "Mid-rise suits most body types; high-rise is great with tucked-in shirts."], ["Mind the stretch", "2% elastane gives comfort without bagging out by evening."]] },
    { title: "Winter Layering Guide for Dhaka's Short Cold Season", excerpt: "Dhaka winters are brief — here's how to layer smart without overheating by noon.", cover: "bomberJacket", tags: ["winter", "style"],
      points: [["Start with a breathable base", "A cotton tee or shirt keeps you comfortable indoors."], ["Add a light mid-layer", "A sweatshirt or cardigan handles chilly mornings."], ["Finish with a jacket", "A bomber or puffer comes off easily when the sun comes out."]] },
  ],
  about: [
    "{store} started in 2019 as a small Facebook page run from a spare room in Dhanmondi. Today we design, source and ship modern fashion to customers in all 64 districts of Bangladesh.",
    "Every piece is quality-checked in our Dhaka studio before it's packed. We work directly with weavers in Narayanganj and Tangail for our ethnic collection, and partner with compliant factories for our everyday wear.",
    "Our promise is simple: honest prices, real product photos, cash on delivery everywhere and hassle-free 7-day exchanges.",
  ],
  perks: ["Cash on delivery across Bangladesh", "Free exchange within 7 days"],
  reviews: [
    "Fabric quality is excellent, exactly like the photos.", "Fit is perfect, I followed the size chart.", "Colour is slightly darker than the picture but still very nice.",
    "Stitching is neat and the packaging was beautiful.", "Got so many compliments at the Eid party!", "Ordered M, fits true to size.", "Delivered in Chattogram within 3 days. Very happy.",
  ],
};
