import type { Catalog } from "./types";

const W = (...values: string[]) => [{ name: "Weight", values }];

export const grocery: Catalog = {
  key: "grocery",
  vendor: "FreshMart",
  freeShippingOver: 1500,
  qty: [[1, 55], [2, 30], [3, 10], [4, 5]],
  collections: [
    { slug: "fresh-fruits", title: "Fresh Fruits", description: "Seasonal, hand-picked fruits delivered the same day.", img: "fruitsMix" },
    { slug: "vegetables", title: "Vegetables", description: "Farm-fresh deshi vegetables sourced every morning from Kawran Bazar.", img: "vegMarket" },
    { slug: "meat-fish", title: "Meat & Fish", description: "Halal meat and river fish, cleaned and cut to order.", img: "meatBoard" },
    { slug: "dairy-eggs-bakery", title: "Dairy, Eggs & Bakery", description: "Milk, eggs and fresh bread for your breakfast table.", img: "eggsTray" },
    { slug: "rice-oil-staples", title: "Rice, Oil & Staples", description: "Everyday pantry staples at fair prices.", img: "rice" },
    { slug: "snacks-beverages", title: "Snacks & Beverages", description: "Tea-time treats, drinks and pantry snacks.", img: "chocoCookies" },
  ],
  products: [
    { t: "Himsagar Mango (Rajshahi)", price: 180, img: ["mangoes", "mango"], vendor: "Rajshahi Orchards", type: "Fruit", col: ["fresh-fruits"], feat: true, pop: 3,
      d: "Sweet, fibre-less Himsagar mangoes picked at peak ripeness from Rajshahi orchards — carbide free.", h: ["Carbide & formalin free", "Hand-picked seasonal harvest"], opt: W("1 kg", "3 kg", "5 kg"), abs: { "1 kg": 180, "3 kg": 520, "5 kg": 850 }, tags: ["seasonal", "mango"] },
    { t: "Sagor Banana", price: 65, img: ["bananas", "bananasPile"], type: "Fruit", col: ["fresh-fruits"], pop: 3,
      d: "Naturally ripened sagor kola — perfect for breakfast and smoothies.", opt: [{ name: "Pack", values: ["Half dozen", "1 dozen"] }], abs: { "Half dozen": 65, "1 dozen": 120 }, tags: ["banana"] },
    { t: "Fuji Apple", price: 175, img: ["apples", "apple"], type: "Fruit", col: ["fresh-fruits"], feat: true, pop: 2,
      d: "Crisp and juicy imported Fuji apples.", opt: W("500 g", "1 kg"), abs: { "500 g": 175, "1 kg": 340 }, tags: ["apple", "imported"] },
    { t: "Malta (Sweet Orange)", price: 280, img: ["oranges", "orangeSlices", "tangerine"], type: "Fruit", col: ["fresh-fruits"], pop: 1.5,
      d: "Juicy, vitamin-C rich malta — great for fresh juice.", opt: W("1 kg"), abs: { "1 kg": 280 }, tags: ["citrus"] },
    { t: "Fresh Strawberries (250 g box)", price: 450, img: ["strawberries", "strawberry"], type: "Fruit", col: ["fresh-fruits"], pop: 0.8, d: "Sweet local strawberries from Rajshahi farms, packed in a protective box.", tags: ["berries", "seasonal"] },
    { t: "Deshi Potato", price: 55, img: ["potatoes"], type: "Vegetable", col: ["vegetables"], pop: 4,
      d: "Everyday deshi alu from Munshiganj.", opt: W("1 kg", "3 kg"), abs: { "1 kg": 55, "3 kg": 160 }, tags: ["staple"] },
    { t: "Deshi Red Onion", price: 95, img: ["onions"], type: "Vegetable", col: ["vegetables"], feat: true, pop: 4,
      d: "Pungent deshi peyaj from Faridpur — the base of every Bangladeshi curry.", opt: W("1 kg", "3 kg"), abs: { "1 kg": 95, "3 kg": 280 }, tags: ["staple"] },
    { t: "Fresh Tomato", price: 60, img: ["tomatoes"], type: "Vegetable", col: ["vegetables"], pop: 2.5,
      d: "Firm, ripe tomatoes for salads and cooking.", opt: W("500 g", "1 kg"), abs: { "500 g": 60, "1 kg": 110 }, tags: ["vegetable"] },
    { t: "Green Chili (250 g)", price: 40, img: ["chili", "redChilies"], type: "Vegetable", col: ["vegetables"], pop: 3, d: "Hot, fresh kacha morich.", tags: ["vegetable"] },
    { t: "Fresh Carrot (500 g)", price: 45, img: ["carrots"], type: "Vegetable", col: ["vegetables"], pop: 1.5, d: "Sweet winter carrots — great for halwa and salads.", tags: ["vegetable"] },
    { t: "Broiler Chicken (Skin-off, cut)", price: 320, img: ["rawChicken"], type: "Meat", col: ["meat-fish"], feat: true, pop: 3,
      d: "Halal broiler chicken, skin removed and cut into curry pieces.", h: ["Halal slaughtered", "Cleaned & cut to curry size"], opt: W("1 kg", "2 kg"), abs: { "1 kg": 320, "2 kg": 630 }, tags: ["halal", "chicken"] },
    { t: "Premium Beef (Bone-in)", price: 780, img: ["meatBoard", "steak"], type: "Meat", col: ["meat-fish"], pop: 2,
      d: "Fresh deshi beef, cut to curry size with the right mix of bone and meat.", opt: W("1 kg", "2 kg"), abs: { "1 kg": 780, "2 kg": 1540 }, tags: ["halal", "beef"] },
    { t: "Rui Fish (Whole, cleaned)", price: 420, img: ["fishPair"], type: "Fish", col: ["meat-fish"], pop: 1.5, d: "River rui, scaled, cleaned and cut on request.", opt: W("1 kg"), abs: { "1 kg": 420 }, tags: ["fish"] },
    { t: "Tiger Prawn / Bagda Chingri (500 g)", price: 850, img: ["shrimp"], type: "Fish", col: ["meat-fish"], pop: 0.8, d: "Large Khulna bagda prawns, deveined and ready to cook.", tags: ["prawn", "seafood"] },
    { t: "Farm Fresh Brown Eggs", price: 165, img: ["eggsTray", "eggsBowl"], type: "Eggs", col: ["dairy-eggs-bakery"], feat: true, pop: 4,
      d: "Fresh brown eggs from partner farms in Gazipur.", opt: [{ name: "Pack", values: ["12 pcs", "30 pcs"] }], abs: { "12 pcs": 165, "30 pcs": 400 }, tags: ["eggs"] },
    { t: "Pasteurized Liquid Milk (1 L)", price: 100, img: ["milk", "milkCarton"], type: "Dairy", col: ["dairy-eggs-bakery"], pop: 3, d: "Fresh pasteurized cow's milk, delivered chilled.", tags: ["milk"] },
    { t: "Whole Wheat Bread (350 g)", price: 85, img: ["breadSliced", "breadLoaves"], type: "Bakery", col: ["dairy-eggs-bakery"], pop: 2, d: "Soft whole wheat sandwich loaf, baked fresh every morning.", tags: ["bread"] },
    { t: "Miniket Rice", price: 390, img: ["rice", "riceBowl"], type: "Rice", col: ["rice-oil-staples"], feat: true, pop: 3,
      d: "Premium polished miniket rice — soft, fluffy and non-sticky.", opt: W("5 kg", "10 kg", "25 kg"), abs: { "5 kg": 390, "10 kg": 760, "25 kg": 1850 }, tags: ["rice", "staple"] },
    { t: "Sundarbans Natural Honey (500 g)", price: 650, img: ["honey"], type: "Honey", col: ["rice-oil-staples"], pop: 1, d: "Raw khalisha honey collected from the Sundarbans mangrove forest.", tags: ["honey", "natural"] },
    { t: "Californian Almonds", price: 380, img: ["almonds"], type: "Dry Fruits", col: ["snacks-beverages"], pop: 1.2,
      d: "Crunchy, protein-packed premium almonds.", opt: W("250 g", "500 g"), abs: { "250 g": 380, "500 g": 740 }, tags: ["nuts", "healthy"] },
    // Extended catalogue
    { t: "Seedless Black Grapes (500 g)", price: 360, img: ["grapes"], type: "Fruit", col: ["fresh-fruits"], ext: true, pop: 0.8, d: "Sweet, seedless imported grapes.", tags: ["imported"] },
    { t: "Watermelon (approx. 3 kg)", price: 280, img: ["watermelon"], type: "Fruit", col: ["fresh-fruits"], ext: true, pop: 1, d: "Juicy red watermelon — summer in a bite.", tags: ["seasonal"] },
    { t: "Honey Queen Pineapple", price: 90, img: ["pineapple"], type: "Fruit", col: ["fresh-fruits"], ext: true, pop: 1, d: "Sweet Madhupur pineapple, per piece.", tags: ["seasonal"] },
    { t: "Cucumber (500 g)", price: 40, img: ["cucumbers"], type: "Vegetable", col: ["vegetables"], ext: true, pop: 2, d: "Crunchy fresh shosha for salads.", tags: ["vegetable"] },
    { t: "Lemon (4 pcs)", price: 40, img: ["lemons"], type: "Vegetable", col: ["vegetables"], ext: true, pop: 2, d: "Juicy kagoji lebu.", tags: ["vegetable"] },
    { t: "Palong Shak (Spinach, 1 bundle)", price: 30, img: ["spinach"], type: "Vegetable", col: ["vegetables"], ext: true, pop: 1.5, d: "Tender spinach leaves, washed and bundled.", tags: ["leafy"] },
    { t: "Norwegian Salmon Fillet (500 g)", price: 1650, img: ["salmon"], type: "Fish", col: ["meat-fish"], ext: true, pop: 0.3, d: "Imported frozen salmon fillet, skin-on.", tags: ["seafood", "imported"] },
    { t: "Chinigura Aromatic Rice (1 kg)", price: 165, img: ["riceBowl", "rice"], type: "Rice", col: ["rice-oil-staples"], ext: true, pop: 1.5, d: "Fragrant small-grain rice for polao and biryani.", tags: ["rice"] },
    { t: "Kabuli Chickpeas (500 g)", price: 95, img: ["chickpeas"], type: "Pulses", col: ["rice-oil-staples"], ext: true, pop: 1, d: "Large white chickpeas for chotpoti and curries.", tags: ["pulses"] },
    { t: "Extra Virgin Olive Oil (500 ml)", price: 850, img: ["oil"], type: "Oil", col: ["rice-oil-staples"], ext: true, pop: 0.6, d: "Cold-pressed Spanish extra virgin olive oil.", tags: ["oil", "imported"] },
    { t: "Whole Spice Combo Pack", price: 450, img: ["spiceBowls", "spices", "spiceSpoons"], type: "Spices", col: ["rice-oil-staples"], ext: true, pop: 1, d: "Cardamom, cinnamon, cloves, bay leaf and cumin — everything for biryani night.", tags: ["spices"] },
    { t: "Chocolate Chip Cookies (300 g)", price: 220, img: ["chocoCookies"], type: "Snacks", col: ["snacks-beverages"], ext: true, pop: 1.2, d: "Freshly baked, loaded with chocolate chunks.", tags: ["snacks"] },
    { t: "Instant Noodles Family Pack (8 pcs)", price: 150, img: ["noodles"], type: "Snacks", col: ["snacks-beverages"], ext: true, pop: 2, d: "Masala-flavoured instant noodles, ready in 2 minutes.", tags: ["snacks"] },
    { t: "Potato Chips Party Pack", price: 120, img: ["chips"], type: "Snacks", col: ["snacks-beverages"], ext: true, pop: 1.5, d: "Assorted baked chips for movie nights.", tags: ["snacks"] },
    { t: "Coca-Cola Can (6 × 250 ml)", price: 240, img: ["cola"], type: "Beverage", col: ["snacks-beverages"], ext: true, pop: 1.5, d: "Chilled Coca-Cola in 250 ml cans.", tags: ["drinks"] },
    { t: "Premium Ground Coffee (250 g)", price: 950, img: ["coffeeBag"], type: "Beverage", col: ["snacks-beverages"], ext: true, pop: 0.5, d: "Medium-roast arabica, ground for drip and French press.", tags: ["coffee"] },
    { t: "Lemon Iced Tea (1 L)", price: 180, img: ["lemonTea", "icedTea"], type: "Beverage", col: ["snacks-beverages"], ext: true, pop: 0.8, d: "Refreshing lemon iced tea, lightly sweetened.", tags: ["drinks"] },
  ],
  blog: [
    { title: "How to Pick the Sweetest Mangoes This Season", excerpt: "Himsagar, Langra or Amrapali? A quick guide to Bangladesh's favourite fruit.", cover: "mangoes", tags: ["seasonal", "guide"],
      points: [["Smell the stem", "A ripe mango smells sweet and fruity near the stem."], ["Press gently", "It should give slightly — like a ripe avocado."], ["Avoid carbide", "Uneven patchy colour can be a sign of artificial ripening. Ours are always carbide free."]] },
    { title: "Weekly Meal Prep on a Budget", excerpt: "Feed a family of four for a week with smart bulk buying and a little Sunday prep.", cover: "vegMarket", tags: ["budget", "meal-prep"],
      points: [["Buy staples in bulk", "Rice, onion and potatoes are cheaper in 5 kg+ packs."], ["Prep your masala", "Blend onion-garlic-ginger paste once and refrigerate for the week."], ["Plan around protein", "Alternate chicken, fish, eggs and dal to keep costs down."]] },
    { title: "Five Refreshing Summer Drinks to Beat the Heat", excerpt: "From borhani to lemon mint — easy coolers made with ingredients from your kitchen.", cover: "watermelon", tags: ["recipes", "summer"],
      points: [["Watermelon cooler", "Blend watermelon, a pinch of salt and lemon juice. Serve over ice."], ["Lebu pani", "Lemon, sugar, black salt and mint — the classic."], ["Iced tea", "Brew strong tea, cool, and add lemon slices and honey."]] },
  ],
  about: [
    "{store} delivers fresh groceries across Dhaka within hours. We source vegetables and fish every morning from wholesale markets and partner farms, so what reaches your door is always fresh.",
    "We started in 2020 during lockdown to help families shop safely from home. Today we serve over 20,000 households with more than 1,500 products.",
    "Order before 2pm for same-day delivery inside Dhaka. Not happy with an item? Our rider will take it back on the spot.",
  ],
  perks: ["Same-day delivery inside Dhaka", "Return on the spot if not fresh"],
  reviews: [
    "Very fresh, much better than the local bazar.", "Delivery was on time, rider was polite.", "Good quality and fair price.", "Packed nicely, nothing was damaged.",
    "Will order every week now.", "Weight was accurate, checked myself.", "Fish was cleaned perfectly.",
  ],
};
