import type { Catalog } from "./types";

export const home: Catalog = {
  key: "home",
  vendor: "Nest Living",
  freeShippingOver: 20000,
  qty: [[1, 88], [2, 12]],
  collections: [
    { slug: "living-room", title: "Living Room", description: "Sofas, armchairs and accents for the heart of your home.", img: "livingWarm" },
    { slug: "bedroom", title: "Bedroom", description: "Beds, bedside tables and soft furnishings for restful nights.", img: "luxBedroom" },
    { slug: "dining", title: "Dining", description: "Tables and chairs made for long family dinners.", img: "diningSet" },
    { slug: "lighting", title: "Lighting", description: "Floor lamps and pendants that set the mood.", img: "floorLamp" },
    { slug: "decor", title: "Decor & Plants", description: "Vases, rugs, clocks and greenery to finish every room.", img: "bohoLiving" },
    { slug: "home-office", title: "Home Office", description: "Desks and shelving for productive work-from-home days.", img: "homeOffice" },
  ],
  products: [
    { t: "Velvet 3-Seater Sofa — Emerald", price: 64500, cmp: 72000, img: ["greenSofa", "livingGreen"], type: "Sofa", col: ["living-room"], feat: true, pop: 1.2,
      d: "Deep-seated velvet sofa on solid mahogany legs, built in our Gazipur workshop.", specs: [["Dimensions", "213 × 88 × 84 cm"], ["Frame", "Kiln-dried mahogany"], ["Fabric", "Stain-resistant velvet"], ["Delivery", "Free assembly inside Dhaka"]],
      opt: [{ name: "Color", values: ["Emerald", "Navy", "Mustard"] }], stock: [2, 6], tags: ["sofa", "velvet"] },
    { t: "Tufted Fabric Sofa — Grey", price: 58500, img: ["greySofa", "livingClassic"], type: "Sofa", col: ["living-room"], pop: 1,
      d: "Button-tufted back and plush cushions in a durable linen-look fabric.", specs: [["Dimensions", "205 × 90 × 86 cm"], ["Frame", "Solid gamari wood"], ["Seat", "High-density foam"]], stock: [2, 6], tags: ["sofa"] },
    { t: "Mid-Century Leather Sofa — Cognac", price: 89500, img: ["leatherSofa", "loftLiving"], type: "Sofa", col: ["living-room"], feat: true, pop: 0.6,
      d: "Top-grain leather that develops a beautiful patina over the years.", specs: [["Dimensions", "220 × 92 × 80 cm"], ["Upholstery", "Top-grain leather"], ["Warranty", "5 years on frame"]], stock: [1, 3], tags: ["sofa", "leather"] },
    { t: "Mustard Accent Armchair", price: 18500, img: ["yellowArmchairRoom", "sofaSun"], type: "Armchair", col: ["living-room"], pop: 1.4,
      d: "A cheerful statement chair with a curved back and tapered legs.", specs: [["Dimensions", "72 × 76 × 82 cm"], ["Legs", "Solid oak"]], stock: [3, 10], tags: ["chair", "accent"] },
    { t: "Tufted Vanity Chair — Ivory", price: 12500, img: ["whiteArmchair"], type: "Chair", col: ["bedroom"], pop: 1, d: "Elegant tufted chair with turned legs — perfect for a dressing table.", specs: [["Dimensions", "58 × 55 × 80 cm"]], stock: [3, 10], tags: ["chair"] },
    { t: "Molded Shell Lounge Chair", price: 15500, img: ["shellChair"], type: "Chair", col: ["living-room", "home-office"], pop: 0.9, d: "Sculptural bent-plywood shell with a padded seat.", specs: [["Dimensions", "90 × 80 × 74 cm"]], stock: [2, 8], tags: ["chair", "designer"] },
    { t: "Scandinavian Dining Chair (Set of 2)", price: 11500, img: ["blackChair", "diningBoho"], type: "Dining Chair", col: ["dining"], feat: true, pop: 2,
      d: "Padded seat on beech wood legs — comfortable for long dinners.", specs: [["Seat height", "46 cm"], ["Legs", "Solid beech"]], opt: [{ name: "Color", values: ["Black", "White", "Grey"] }], stock: [4, 12], tags: ["dining", "chair"] },
    { t: "Upholstered Bed Frame", price: 62500, img: ["tuftedBed", "luxBedroom"], type: "Bed", col: ["bedroom"], feat: true, pop: 1,
      d: "A tall tufted headboard with a solid slatted base — no box spring needed.", specs: [["Frame", "Solid gamari wood"], ["Headboard", "Linen-blend, button tufted"]],
      opt: [{ name: "Size", values: ["Queen (5 × 6.5 ft)", "King (6 × 7 ft)"] }], delta: { "King (6 × 7 ft)": 10000 }, stock: [1, 5], tags: ["bed"] },
    { t: "Nordic Bedside Table", price: 8950, img: ["bedside", "sideTable"], type: "Bedside Table", col: ["bedroom"], pop: 1.5, d: "Compact two-tone nightstand with a soft-close drawer.", specs: [["Dimensions", "45 × 40 × 55 cm"]], stock: [4, 14], tags: ["bedroom", "storage"] },
    { t: "Solid Wood 6-Seater Dining Set", price: 78500, img: ["diningSet", "roundTable"], type: "Dining Set", col: ["dining"], pop: 0.5,
      d: "Oval teak-finish table with six matching chairs.", specs: [["Table", "180 × 90 cm"], ["Material", "Solid teak veneer on mahogany"]], stock: [1, 3], tags: ["dining"] },
    { t: "Industrial Floor Lamp", price: 8950, img: ["floorLamp", "livingWarm"], type: "Lamp", col: ["lighting"], pop: 1.2, d: "Adjustable metal shade on a slim steel stand.", specs: [["Height", "155 cm"], ["Bulb", "E27, max 40W (not included)"]], stock: [4, 12], tags: ["lighting"] },
    { t: "Scandi Pendant Light", price: 4950, img: ["pendantLamp"], type: "Pendant", col: ["lighting"], pop: 1.2, d: "Matte dome pendant — perfect over a dining table or kitchen island.", specs: [["Diameter", "38 cm"], ["Cable", "150 cm adjustable"]], stock: [5, 15], tags: ["lighting"] },
    { t: "Minimal Ceramic Vase", price: 1850, img: ["whiteVase", "vaseMinimal"], type: "Vase", col: ["decor"], pop: 2, d: "Hand-glazed matte ceramic vase for dried stems or fresh flowers.", stock: [8, 25], tags: ["decor", "ceramic"] },
    { t: "Potted Succulent in Ceramic Pot", price: 950, img: ["succulent", "cactus", "plantsRow"], type: "Plant", col: ["decor"], pop: 2.5, d: "Low-maintenance succulent in a pastel ceramic pot. Water once a week.", stock: [10, 30], tags: ["plants", "gift"] },
    { t: "Hand-Knotted Area Rug (5 × 8 ft)", price: 16500, img: ["rugRoll", "livingBeige"], type: "Rug", col: ["decor", "living-room"], pop: 0.8, d: "Soft wool-blend rug with a vintage-inspired medallion pattern.", stock: [2, 8], tags: ["rug"] },
    { t: "Silent Sweep Wall Clock", price: 2450, img: ["wallClock"], type: "Clock", col: ["decor"], pop: 1.5, d: "30 cm minimalist wall clock with a silent sweep movement.", stock: [8, 20], tags: ["decor"] },
    { t: "Solid Wood Study Desk", price: 22500, img: ["woodDesk", "homeOffice"], type: "Desk", col: ["home-office"], feat: true, pop: 1, d: "Clean-lined desk with a cable cut-out and drawer.", specs: [["Dimensions", "120 × 60 × 75 cm"], ["Material", "Solid mahogany"]], stock: [2, 8], tags: ["office"] },
    { t: "Floating Wall Shelf Set (3 pcs)", price: 4250, img: ["floatingShelf"], type: "Shelf", col: ["home-office", "decor"], pop: 1.2, d: "Wall-mounted shelves with hidden brackets.", stock: [5, 15], tags: ["storage"] },
    { t: "Scented Soy Candle — Sandalwood", price: 1250, img: ["candleGlow"], type: "Candle", col: ["decor"], pop: 1.8, d: "Hand-poured soy candle with a 40-hour burn time.", stock: [10, 30], tags: ["candle", "gift"] },
    { t: "Hotel Collection Pillow (Pair)", price: 2450, img: ["pillow", "bedside"], type: "Pillow", col: ["bedroom"], pop: 2, d: "Plush microfibre pillows with a 300TC cotton cover.", stock: [10, 30], tags: ["bedding"] },
  ],
  blog: [
    { title: "Small Apartment, Big Style: 7 Ideas for Dhaka Flats", excerpt: "Make a 1,000 sq ft flat feel twice as big with the right furniture and layout.", cover: "livingBright", tags: ["small-spaces", "ideas"],
      points: [["Go leggy", "Furniture on raised legs shows more floor and feels lighter."], ["Mirror magic", "A large mirror opposite a window doubles your daylight."], ["Multi-task", "A bedside table that doubles as a desk saves precious space."]] },
    { title: "How to Choose the Right Sofa Size", excerpt: "Measure twice, buy once — a simple guide to sofa sizing.", cover: "greenSofa", tags: ["guide", "sofa"],
      points: [["Measure the wall", "Leave at least 45 cm on each side of the sofa."], ["Check the stairs", "Measure lift doors and staircases before ordering."], ["Seat depth", "Deep seats for lounging, standard for upright sitting."]] },
    { title: "Styling Your Home for Eid", excerpt: "Quick, affordable updates to welcome guests this Eid.", cover: "bohoLiving", tags: ["eid", "styling"],
      points: [["Swap cushions", "New covers in jewel tones instantly refresh a room."], ["Add greenery", "A few potted plants make any room feel alive."], ["Warm lighting", "Candles and warm bulbs create an inviting glow."]] },
  ],
  about: [
    "{store} crafts furniture that's made to last. Our pieces are built by skilled carpenters in our Gazipur workshop using kiln-dried hardwood.",
    "We design for Bangladeshi homes — furniture that fits real apartment sizes, handles humidity and looks beautiful for years.",
    "Free delivery and assembly inside Dhaka on orders over ৳20,000. Visit our experience centre in Gulshan to see and feel every piece.",
  ],
  perks: ["Free assembly inside Dhaka", "Up to 5-year frame warranty"],
  reviews: [
    "Solid build quality, feels premium.", "Delivery team assembled everything neatly.", "Looks exactly like the pictures.", "Colour matches our living room perfectly.",
    "Very comfortable, worth every taka.", "Took a week to deliver but worth the wait.", "Great finish, no smell.",
  ],
};
