import {
  BarChart3,
  Code2,
  Globe,
  Megaphone,
  Palette,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Store,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export type Feature = {
  id: string;
  icon: LucideIcon;
  title: string;
  short: string;
  headline: string;
  body: string;
  bullets: string[];
  color: string; // tailwind gradient classes for the icon tile
  plan?: string;
};

export const FEATURES: Feature[] = [
  {
    id: "store-builder",
    icon: Store,
    title: "Store builder",
    short: "Launch a complete store in minutes — products, variants, collections, pages, blog and navigation.",
    headline: "Everything a modern store needs, without a developer",
    body: "Products with unlimited variants and inventory, smart collections, content pages, a blog, menus and SEO controls. Bulk import by CSV, bulk edit prices and stock, and publish when you're ready.",
    bullets: ["Variants, SKUs, barcodes & stock tracking", "Collections, tags and filters", "Pages, blog & navigation menus", "SEO titles, meta descriptions & sitemaps", "Delivery zones (inside/outside Dhaka) and charges", "Discount codes, free shipping & automatic offers"],
    color: "from-brand-500 to-indigo-500",
  },
  {
    id: "themes",
    icon: Palette,
    title: "Themes & customizer",
    short: "13 themes for every category and a drag-and-drop section customizer with live preview.",
    headline: "Shopify-grade theming, designed for how Bangladesh shops",
    body: "Every theme is built from sections and blocks you can add, reorder and configure in a live preview — on desktop and mobile. Start from a category preset (Fashion, Grocery, Electronics …) and make it yours in minutes.",
    bullets: ["13 themes across 17 business categories", "Add, reorder & hide sections and blocks", "Global colours, fonts, radius & layout", "Draft changes and publish when ready", "Category presets with sample content", "Premium themes from independent developers"],
    color: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "payments",
    icon: Wallet,
    title: "Local payments",
    short: "bKash, Nagad, SSLCommerz, aamarPay, COD and international cards — configured in minutes.",
    headline: "Take every way Bangladesh pays",
    body: "Cash on delivery with optional advance delivery charge, bKash tokenized checkout, Nagad, SSLCommerz (cards, mobile banking and net banking), aamarPay, manual Send-Money with TrxID verification, plus Stripe and PayPal for international buyers.",
    bullets: ["COD with advance delivery charge", "bKash tokenized & manual Send Money", "Nagad, Rocket & SSLCommerz", "Stripe & PayPal for global customers", "Automatic payment status & IPN verification", "Partial payments and refunds tracking"],
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "couriers",
    icon: Truck,
    title: "Courier automation",
    short: "Book Steadfast, Pathao, RedX and Paperfly parcels in one click and sync statuses automatically.",
    headline: "From order to doorstep in one click",
    body: "Connect your courier accounts once. Book single orders or hundreds in bulk, print labels, and let delivery statuses and COD collections sync back to your orders automatically.",
    bullets: ["Steadfast, Pathao, RedX & Paperfly", "Bulk booking & label printing", "Automatic status sync & customer SMS", "COD reconciliation per consignment", "City/zone mapping for Pathao", "Tracking links on order pages"],
    color: "from-teal-500 to-emerald-500",
  },
  {
    id: "orders",
    icon: ShieldCheck,
    title: "Orders & fraud check",
    short: "See each customer's courier success ratio before you ship, block bad actors, cut failed deliveries.",
    headline: "Stop shipping to people who won't receive",
    body: "Every order shows the customer's delivery success ratio across couriers, their order history with you, and risk flags. Block phone numbers, require advance payment below a threshold, and manage everything from one order timeline.",
    bullets: ["Courier success ratio per phone number", "Minimum success-rate rules", "Phone blocklist & duplicate detection", "Order timeline, notes & tags", "Manual orders from phone & Messenger", "Invoices & packing slips"],
    color: "from-amber-500 to-orange-500",
    plan: "Pro",
  },
  {
    id: "incomplete-orders",
    icon: RotateCcw,
    title: "Incomplete orders",
    short: "Capture checkouts the moment a phone number is typed — then call, SMS and recover.",
    headline: "Win back the customers who almost bought",
    body: "As soon as a shopper enters their phone number at checkout we save the cart. Your team sees every incomplete order with products and contact details, and can convert it to a real order in one click.",
    bullets: ["Captured at phone-number entry", "One-click convert to order", "Recovery SMS templates", "Assign to staff & track outcomes", "Recovered revenue analytics"],
    color: "from-sky-500 to-cyan-500",
    plan: "Growth",
  },
  {
    id: "analytics",
    icon: BarChart3,
    title: "Analytics",
    short: "Sales, orders, conversion, top products, traffic sources and customer cohorts in real time.",
    headline: "Know exactly what's working",
    body: "A real-time dashboard with revenue, orders, average order value and conversion rate, plus product, channel and delivery-zone reports. Export anything to CSV.",
    bullets: ["Revenue, orders, AOV & conversion", "Top products & collections", "Traffic sources & UTM campaigns", "Delivery success by courier", "Returning customers & cohorts", "CSV exports"],
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "marketing",
    icon: Megaphone,
    title: "Marketing pixels",
    short: "Meta Pixel + Conversions API, GA4, Google Tag Manager and TikTok Pixel with e-commerce events.",
    headline: "Accurate tracking for every ad taka you spend",
    body: "Paste an ID and we fire standard e-commerce events — ViewContent, AddToCart, InitiateCheckout and Purchase — from the browser and the server (Meta CAPI) with deduplication, so your ads optimise on real data.",
    bullets: ["Meta Pixel + Conversions API (server-side)", "Google Analytics 4 e-commerce", "Google Tag Manager dataLayer", "TikTok Pixel", "Product feeds for Google & Facebook shops", "Messenger & WhatsApp chat buttons"],
    color: "from-blue-500 to-violet-500",
  },
  {
    id: "ai",
    icon: Sparkles,
    title: "AI product writer",
    short: "Generate persuasive descriptions and SEO meta in Bangla or English from a title and a few keywords.",
    headline: "Great product copy in seconds — in Bangla or English",
    body: "Give the AI writer a product title and a few keywords; it drafts a structured description with benefits and specs, plus SEO title and meta description. Pick the tone that fits your brand.",
    bullets: ["Bangla & English output", "Tone presets (friendly, premium, playful)", "SEO title & meta description", "Works in bulk from the product list"],
    color: "from-fuchsia-500 to-pink-500",
    plan: "Growth",
  },
  {
    id: "staff",
    icon: Users,
    title: "Staff & permissions",
    short: "Invite your team with granular permissions — order processors, catalog editors, marketers.",
    headline: "Grow your team without sharing passwords",
    body: "Invite staff by email and assign role presets or fine-grained permissions for orders, products, customers, discounts, analytics, content, themes, settings, integrations and billing. Every change is recorded in the audit log.",
    bullets: ["14 granular permissions", "Role presets: Manager, Order processor, Catalog editor, Marketer", "Audit log of staff actions", "Multi-store switching"],
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "domains",
    icon: Globe,
    title: "Custom domains",
    short: "Free yourstore.paicommerce.com subdomain, or connect your own domain with automatic SSL.",
    headline: "Your brand, your domain, always secure",
    body: "Every store is live instantly on a paicommerce.com subdomain. Connect your own .com or .com.bd with a single CNAME record; we verify it and issue SSL automatically on our global edge network.",
    bullets: ["Instant subdomain", "Custom domain via CNAME", "Automatic SSL certificates", "Global CDN & image optimisation", "Remove PaiCommerce branding on paid plans"],
    color: "from-cyan-500 to-sky-600",
    plan: "Growth",
  },
  {
    id: "api",
    icon: Code2,
    title: "Developer API & webhooks",
    short: "REST API with scoped API keys and HMAC-signed webhooks to connect ERPs, apps and automations.",
    headline: "Build anything on top of your store",
    body: "A clean REST API for products, collections, customers and orders with scoped API keys, plus webhooks for order and product events signed with HMAC-SHA256. Themes are open React packages built with our Theme SDK.",
    bullets: ["REST API at /api/v1 with scoped keys", "Webhooks: order.created, order.updated, product.updated, customer.created", "HMAC-SHA256 signatures", "Theme SDK & CLI", "Sell themes with 70% revenue share"],
    color: "from-slate-700 to-slate-900",
    plan: "Pro",
  },
];
